vim9script

# Name:         Stella Maris
# Description:  A color scheme for our Star of the Sea.
# Author:       John <jbpjackson+vim@icloud.com>
# URL:          https://sr.ht/~johnridesabike/vim-stella-maris/
# License:      Same as Vim
# Last Change:  2025 May 28

# Generated by Colortemplate v3.0.0-beta3

hi clear
g:colors_name = 'stella'

if &background == 'dark'
  g:terminal_ansi_colors = ['#0d1a16', '#8c4151', '#5c7d3e', '#736439', '#3e4a7d', '#794180', '#38665b', '#95b1ae', '#2f3c39', '#ff758f', '#b9fc7e', '#f2d479', '#7e95fc', '#f382ff', '#7ee6cc', '#e7ffff']

  const transp_bg = get(g:, 'stella_transp_bg', 0)
  const italic = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link CurSearch IncSearch
  hi! link CursorIM Cursor
  hi! link CursorLineFold FoldColumn
  hi! link CursorLineSign SignColumn
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Constant
  hi! link Function Identifier
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link LineNrAbove LineNr
  hi! link LineNrBelow LineNr
  hi! link Macro PreProc
  hi! link MessageWindow WarningMsg
  hi! link Number Constant
  hi! link Operator Statement
  hi! link PopupNotification WarningMsg
  hi! link PopupSelected PmenuSel
  hi! link PreCondit PreProc
  hi! link QuickFixLine Search
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link StorageClass Type
  hi! link String Constant
  hi! link Structure Type
  hi! link Tag Special
  hi! link Typedef Type
  hi! link lCursor Cursor
  hi Normal guifg=#e7ffff guibg=#0d1a16 guisp=NONE gui=NONE ctermfg=195 ctermbg=234 ctermul=NONE cterm=NONE term=NONE
  hi ColorColumn guifg=NONE guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 ctermul=NONE cterm=NONE term=reverse
  hi Comment guifg=#95b1ae guibg=NONE guisp=NONE gui=italic ctermfg=109 ctermbg=NONE ctermul=NONE cterm=italic term=italic
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi Constant guifg=#7ee6cc guibg=NONE guisp=NONE gui=NONE ctermfg=79 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi Cursor guifg=#5c7d3e guibg=#e7ffff guisp=NONE gui=NONE ctermfg=65 ctermbg=195 ctermul=NONE cterm=NONE term=NONE
  hi CursorColumn guifg=NONE guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 ctermul=NONE cterm=NONE term=reverse
  hi CursorLine guifg=NONE guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 ctermul=NONE cterm=NONE term=underline
  hi CursorLineNr guifg=#f2d479 guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=222 ctermbg=237 ctermul=NONE cterm=NONE term=bold,reverse,underline
  hi DiffAdd guifg=#e7ffff guibg=#5c7d3e guisp=NONE gui=NONE ctermfg=195 ctermbg=65 ctermul=NONE cterm=NONE term=reverse,underline
  hi DiffChange guifg=#e7ffff guibg=#736439 guisp=NONE gui=NONE ctermfg=195 ctermbg=58 ctermul=NONE cterm=NONE term=reverse,underline
  hi DiffDelete guifg=#e7ffff guibg=#8c4151 guisp=NONE gui=NONE ctermfg=195 ctermbg=125 ctermul=NONE cterm=NONE term=reverse,underline
  hi DiffText guifg=#0d1a16 guibg=#95b1ae guisp=NONE gui=bold ctermfg=234 ctermbg=109 ctermul=NONE cterm=bold term=bold,reverse,underline
  hi Directory guifg=#7e95fc guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi EndOfBuffer guifg=#7e95fc guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi Error guifg=#e7ffff guibg=#8c4151 guisp=NONE gui=NONE ctermfg=195 ctermbg=125 ctermul=NONE cterm=NONE term=reverse
  hi ErrorMsg guifg=#e7ffff guibg=#8c4151 guisp=NONE gui=NONE ctermfg=195 ctermbg=125 ctermul=NONE cterm=NONE term=bold,reverse
  hi FoldColumn guifg=#7e95fc guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE ctermul=NONE cterm=NONE term=reverse
  hi Folded guifg=#7ee6cc guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=79 ctermbg=237 ctermul=NONE cterm=NONE term=reverse,underline
  hi Identifier guifg=#7e95fc guibg=NONE guisp=NONE gui=bold ctermfg=105 ctermbg=NONE ctermul=NONE cterm=bold term=italic
  hi Ignore guifg=#0d1a16 guibg=#0d1a16 guisp=NONE gui=NONE ctermfg=234 ctermbg=234 ctermul=NONE cterm=NONE term=NONE
  hi IncSearch guifg=#0d1a16 guibg=#b9fc7e guisp=NONE gui=NONE ctermfg=234 ctermbg=156 ctermul=NONE cterm=NONE term=bold,reverse
  hi LineNr guifg=#95b1ae guibg=NONE guisp=NONE gui=NONE ctermfg=109 ctermbg=NONE ctermul=NONE cterm=NONE term=reverse
  hi MatchParen guifg=#e7ffff guibg=#736439 guisp=NONE gui=NONE ctermfg=195 ctermbg=58 ctermul=NONE cterm=NONE term=bold,underline
  hi ModeMsg guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi MoreMsg guifg=#b9fc7e guibg=NONE guisp=NONE gui=NONE ctermfg=156 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi NonText guifg=#7e95fc guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi Pmenu guifg=#e7ffff guibg=#0d1a16 guisp=NONE gui=NONE ctermfg=195 ctermbg=234 ctermul=NONE cterm=NONE term=reverse
  hi PmenuSbar guifg=#e7ffff guibg=#0d1a16 guisp=NONE gui=NONE ctermfg=195 ctermbg=234 ctermul=NONE cterm=NONE term=NONE
  hi PmenuSel guifg=#0d1a16 guibg=#f2d479 guisp=NONE gui=NONE ctermfg=234 ctermbg=222 ctermul=NONE cterm=NONE term=NONE
  hi PmenuThumb guifg=#95b1ae guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=109 ctermbg=237 ctermul=NONE cterm=NONE term=NONE
  hi PreProc guifg=#f382ff guibg=NONE guisp=NONE gui=NONE ctermfg=213 ctermbg=NONE ctermul=NONE cterm=NONE term=italic
  hi Question guifg=#b9fc7e guibg=NONE guisp=NONE gui=NONE ctermfg=156 ctermbg=NONE ctermul=NONE cterm=NONE term=standout
  hi Search guifg=NONE guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 ctermul=NONE cterm=NONE term=underline
  hi SignColumn guifg=#7e95fc guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE ctermul=NONE cterm=NONE term=reverse
  hi Special guifg=#ff758f guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi SpecialKey guifg=#7e95fc guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi SpellBad guifg=NONE guibg=NONE guisp=#ff758f gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=204 cterm=underline term=underline
  hi SpellCap guifg=NONE guibg=NONE guisp=#7e95fc gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=105 cterm=underline term=underline
  hi SpellLocal guifg=NONE guibg=NONE guisp=#7ee6cc gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=79 cterm=underline term=underline
  hi SpellRare guifg=NONE guibg=NONE guisp=#f382ff gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=213 cterm=underline term=underline
  hi Statement guifg=#f2d479 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi StatusLine guifg=#0d1a16 guibg=#95b1ae guisp=NONE gui=NONE ctermfg=234 ctermbg=109 ctermul=NONE cterm=NONE term=bold,reverse
  hi StatusLineNC guifg=#e7ffff guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=195 ctermbg=237 ctermul=NONE cterm=NONE term=reverse
  hi TabLine guifg=#95b1ae guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=109 ctermbg=237 ctermul=NONE cterm=NONE term=reverse,underline
  hi TabLineFill guifg=#0d1a16 guibg=#95b1ae guisp=NONE gui=NONE ctermfg=234 ctermbg=109 ctermul=NONE cterm=NONE term=reverse,underline
  hi TabLineSel guifg=#e7ffff guibg=#0d1a16 guisp=NONE gui=bold ctermfg=195 ctermbg=234 ctermul=NONE cterm=bold term=bold
  hi Terminal guifg=#e7ffff guibg=#0d1a16 guisp=NONE gui=NONE ctermfg=195 ctermbg=234 ctermul=NONE cterm=NONE term=NONE
  hi Title guifg=#f382ff guibg=NONE guisp=NONE gui=bold ctermfg=213 ctermbg=NONE ctermul=NONE cterm=bold term=bold
  hi Todo guifg=#f2d479 guibg=NONE guisp=NONE gui=italic,reverse ctermfg=222 ctermbg=NONE ctermul=NONE cterm=italic,reverse term=bold,underline
  hi ToolbarButton guifg=#0d1a16 guibg=#f2d479 guisp=NONE gui=bold ctermfg=234 ctermbg=222 ctermul=NONE cterm=bold term=bold,reverse
  hi ToolbarLine guifg=NONE guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 ctermul=NONE cterm=NONE term=reverse
  hi Type guifg=#b9fc7e guibg=NONE guisp=NONE gui=NONE ctermfg=156 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi Underlined guifg=#7e95fc guibg=NONE guisp=NONE gui=underline ctermfg=105 ctermbg=NONE ctermul=NONE cterm=underline term=underline
  hi VertSplit guifg=#e7ffff guibg=#2f3c39 guisp=NONE gui=NONE ctermfg=195 ctermbg=237 ctermul=NONE cterm=NONE term=reverse
  hi Visual guifg=#0d1a16 guibg=#e7ffff guisp=NONE gui=NONE ctermfg=234 ctermbg=195 ctermul=NONE cterm=NONE term=reverse
  hi VisualNOS guifg=#e7ffff guibg=#0d1a16 guisp=NONE gui=bold,underline ctermfg=195 ctermbg=234 ctermul=NONE cterm=bold,underline term=NONE
  hi WarningMsg guifg=#ff758f guibg=NONE guisp=NONE gui=NONE ctermfg=204 ctermbg=NONE ctermul=NONE cterm=NONE term=standout
  hi WildMenu guifg=#0d1a16 guibg=#f2d479 guisp=NONE gui=NONE ctermfg=234 ctermbg=222 ctermul=NONE cterm=NONE term=bold
  hi debugBreakpoint guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi debugPC guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE term=NONE

  if empty(&t_Co)
    finish
  endif

  if str2nr(&t_Co) >= 256
    if transp_bg == 1
      hi Normal ctermfg=195 ctermbg=NONE ctermul=NONE cterm=NONE
      hi Terminal ctermfg=195 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    finish
  endif

  if str2nr(&t_Co) >= 8
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    if transp_bg == 1
      hi Normal ctermfg=White ctermbg=NONE ctermul=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    finish
  endif

  if str2nr(&t_Co) >= 0
    hi CursorIM term=NONE
    hi PopupSelected term=reverse
    if transp_bg == 1
      hi Normal term=NONE
      hi Terminal term=NONE
    endif
    finish
  endif
  finish
endif

if &background == 'light'
  g:terminal_ansi_colors = ['#0f0500', '#94011c', '#428507', '#7a5d06', '#071e85', '#7a0587', '#006e52', '#d0d9d9', '#5a5350', '#ff8299', '#b0e880', '#ffe28c', '#8093e8', '#f48fff', '#99ffe6', '#faffff']

  const transp_bg = get(g:, 'stella_transp_bg', 0)
  const italic = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link CurSearch IncSearch
  hi! link CursorIM Cursor
  hi! link CursorLineFold FoldColumn
  hi! link CursorLineSign SignColumn
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Constant
  hi! link Function Identifier
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link LineNrAbove LineNr
  hi! link LineNrBelow LineNr
  hi! link Macro PreProc
  hi! link MessageWindow WarningMsg
  hi! link Number Constant
  hi! link Operator Statement
  hi! link PopupNotification WarningMsg
  hi! link PopupSelected PmenuSel
  hi! link PreCondit PreProc
  hi! link QuickFixLine Search
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link StorageClass Type
  hi! link String Constant
  hi! link Structure Type
  hi! link Tag Special
  hi! link Typedef Type
  hi! link lCursor Cursor
  hi Normal guifg=#0f0500 guibg=#faffff guisp=NONE gui=NONE ctermfg=232 ctermbg=231 ctermul=NONE cterm=NONE term=NONE
  hi ColorColumn guifg=NONE guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=188 ctermul=NONE cterm=NONE term=reverse
  hi Comment guifg=#5a5350 guibg=NONE guisp=NONE gui=italic ctermfg=240 ctermbg=NONE ctermul=NONE cterm=italic term=italic
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi Constant guifg=#071e85 guibg=NONE guisp=NONE gui=NONE ctermfg=18 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi Cursor guifg=#b0e880 guibg=#5a5350 guisp=NONE gui=NONE ctermfg=150 ctermbg=240 ctermul=NONE cterm=NONE term=NONE
  hi CursorColumn guifg=NONE guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=188 ctermul=NONE cterm=NONE term=reverse
  hi CursorLine guifg=NONE guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=188 ctermul=NONE cterm=NONE term=underline
  hi CursorLineNr guifg=#7a0587 guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=90 ctermbg=188 ctermul=NONE cterm=NONE term=bold,reverse,underline
  hi DiffAdd guifg=#0f0500 guibg=#b0e880 guisp=NONE gui=NONE ctermfg=232 ctermbg=150 ctermul=NONE cterm=NONE term=reverse,underline
  hi DiffChange guifg=#0f0500 guibg=#ffe28c guisp=NONE gui=NONE ctermfg=232 ctermbg=222 ctermul=NONE cterm=NONE term=reverse,underline
  hi DiffDelete guifg=#0f0500 guibg=#ff8299 guisp=NONE gui=NONE ctermfg=232 ctermbg=211 ctermul=NONE cterm=NONE term=reverse,underline
  hi DiffText guifg=#faffff guibg=#5a5350 guisp=NONE gui=bold ctermfg=231 ctermbg=240 ctermul=NONE cterm=bold term=bold,reverse,underline
  hi Directory guifg=#006e52 guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi EndOfBuffer guifg=#006e52 guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi Error guifg=#0f0500 guibg=#ff8299 guisp=NONE gui=NONE ctermfg=232 ctermbg=211 ctermul=NONE cterm=NONE term=reverse
  hi ErrorMsg guifg=#0f0500 guibg=#ff8299 guisp=NONE gui=NONE ctermfg=232 ctermbg=211 ctermul=NONE cterm=NONE term=bold,reverse
  hi FoldColumn guifg=#006e52 guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE ctermul=NONE cterm=NONE term=reverse
  hi Folded guifg=#071e85 guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=18 ctermbg=188 ctermul=NONE cterm=NONE term=reverse,underline
  hi Identifier guifg=#006e52 guibg=NONE guisp=NONE gui=bold ctermfg=29 ctermbg=NONE ctermul=NONE cterm=bold term=italic
  hi Ignore guifg=#faffff guibg=#faffff guisp=NONE gui=NONE ctermfg=231 ctermbg=231 ctermul=NONE cterm=NONE term=NONE
  hi IncSearch guifg=#faffff guibg=#428507 guisp=NONE gui=NONE ctermfg=231 ctermbg=28 ctermul=NONE cterm=NONE term=bold,reverse
  hi LineNr guifg=#5a5350 guibg=NONE guisp=NONE gui=NONE ctermfg=240 ctermbg=NONE ctermul=NONE cterm=NONE term=reverse
  hi MatchParen guifg=#0f0500 guibg=#ffe28c guisp=NONE gui=NONE ctermfg=232 ctermbg=222 ctermul=NONE cterm=NONE term=bold,underline
  hi ModeMsg guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi MoreMsg guifg=#428507 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi NonText guifg=#006e52 guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi Pmenu guifg=#0f0500 guibg=#faffff guisp=NONE gui=NONE ctermfg=232 ctermbg=231 ctermul=NONE cterm=NONE term=reverse
  hi PmenuSbar guifg=#0f0500 guibg=#faffff guisp=NONE gui=NONE ctermfg=232 ctermbg=231 ctermul=NONE cterm=NONE term=NONE
  hi PmenuSel guifg=#0f0500 guibg=#ffe28c guisp=NONE gui=NONE ctermfg=232 ctermbg=222 ctermul=NONE cterm=NONE term=NONE
  hi PmenuThumb guifg=#d0d9d9 guibg=#5a5350 guisp=NONE gui=NONE ctermfg=188 ctermbg=240 ctermul=NONE cterm=NONE term=NONE
  hi PreProc guifg=#7a0587 guibg=NONE guisp=NONE gui=NONE ctermfg=90 ctermbg=NONE ctermul=NONE cterm=NONE term=italic
  hi Question guifg=#428507 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE ctermul=NONE cterm=NONE term=standout
  hi Search guifg=NONE guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=188 ctermul=NONE cterm=NONE term=underline
  hi SignColumn guifg=#006e52 guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE ctermul=NONE cterm=NONE term=reverse
  hi Special guifg=#94011c guibg=NONE guisp=NONE gui=NONE ctermfg=88 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi SpecialKey guifg=#006e52 guibg=NONE guisp=NONE gui=NONE ctermfg=29 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi SpellBad guifg=NONE guibg=NONE guisp=#ff8299 gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=211 cterm=underline term=underline
  hi SpellCap guifg=NONE guibg=NONE guisp=#006e52 gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=29 cterm=underline term=underline
  hi SpellLocal guifg=NONE guibg=NONE guisp=#071e85 gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=18 cterm=underline term=underline
  hi SpellRare guifg=NONE guibg=NONE guisp=#7a0587 gui=undercurl ctermfg=NONE ctermbg=NONE ctermul=90 cterm=underline term=underline
  hi Statement guifg=#7a5d06 guibg=NONE guisp=NONE gui=NONE ctermfg=94 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi StatusLine guifg=#0f0500 guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=232 ctermbg=188 ctermul=NONE cterm=NONE term=bold,reverse
  hi StatusLineNC guifg=#faffff guibg=#5a5350 guisp=NONE gui=NONE ctermfg=231 ctermbg=240 ctermul=NONE cterm=NONE term=reverse
  hi TabLine guifg=#5a5350 guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=240 ctermbg=188 ctermul=NONE cterm=NONE term=reverse,underline
  hi TabLineFill guifg=#faffff guibg=#5a5350 guisp=NONE gui=NONE ctermfg=231 ctermbg=240 ctermul=NONE cterm=NONE term=reverse,underline
  hi TabLineSel guifg=#0f0500 guibg=#faffff guisp=NONE gui=bold ctermfg=232 ctermbg=231 ctermul=NONE cterm=bold term=bold
  hi Terminal guifg=#0f0500 guibg=#faffff guisp=NONE gui=NONE ctermfg=232 ctermbg=231 ctermul=NONE cterm=NONE term=NONE
  hi Title guifg=#7a0587 guibg=NONE guisp=NONE gui=bold ctermfg=90 ctermbg=NONE ctermul=NONE cterm=bold term=bold
  hi Todo guifg=#7a5d06 guibg=NONE guisp=NONE gui=italic,reverse ctermfg=94 ctermbg=NONE ctermul=NONE cterm=italic,reverse term=bold,underline
  hi ToolbarButton guifg=#0f0500 guibg=#ffe28c guisp=NONE gui=bold ctermfg=232 ctermbg=222 ctermul=NONE cterm=bold term=bold,reverse
  hi ToolbarLine guifg=NONE guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=NONE ctermbg=188 ctermul=NONE cterm=NONE term=reverse
  hi Type guifg=#428507 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE ctermul=NONE cterm=NONE term=bold
  hi Underlined guifg=#071e85 guibg=NONE guisp=NONE gui=underline ctermfg=18 ctermbg=NONE ctermul=NONE cterm=underline term=underline
  hi VertSplit guifg=#5a5350 guibg=#d0d9d9 guisp=NONE gui=NONE ctermfg=240 ctermbg=188 ctermul=NONE cterm=NONE term=reverse
  hi Visual guifg=#faffff guibg=#0f0500 guisp=NONE gui=NONE ctermfg=231 ctermbg=232 ctermul=NONE cterm=NONE term=reverse
  hi VisualNOS guifg=#0f0500 guibg=#faffff guisp=NONE gui=bold,underline ctermfg=232 ctermbg=231 ctermul=NONE cterm=bold,underline term=NONE
  hi WarningMsg guifg=#94011c guibg=NONE guisp=NONE gui=NONE ctermfg=88 ctermbg=NONE ctermul=NONE cterm=NONE term=standout
  hi WildMenu guifg=#5a5350 guibg=#ffe28c guisp=NONE gui=NONE ctermfg=240 ctermbg=222 ctermul=NONE cterm=NONE term=bold
  hi debugBreakpoint guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE term=NONE
  hi debugPC guifg=fg guibg=NONE guisp=NONE gui=NONE ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE term=NONE

  if empty(&t_Co)
    finish
  endif

  if str2nr(&t_Co) >= 256
    if transp_bg == 1
      hi Normal ctermfg=232 ctermbg=NONE ctermul=NONE cterm=NONE
      hi Terminal ctermfg=232 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    finish
  endif

  if str2nr(&t_Co) >= 8
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    if transp_bg == 1
      hi Normal ctermfg=Black ctermbg=NONE ctermul=NONE cterm=NONE
      hi Terminal ctermfg=Black ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    finish
  endif

  if str2nr(&t_Co) >= 0
    hi CursorIM term=NONE
    hi PopupSelected term=reverse
    if transp_bg == 1
      hi Normal term=NONE
      hi Terminal term=NONE
    endif
    finish
  endif
  finish
endif

# vim: et ts=8 sw=2 sts=2
