" Name:         Stella Maris
" Description:  A color scheme for our Star of the Sea.
" Author:       John <jbpjackson+vim@icloud.com>
" Maintainer:   John <jbpjackson+vim@icloud.com>
" Website:      https://github.com/johnridesabike/vim-stella-maris
" License:      Same as Vim
" Last Updated: Sun Jun 11 19:09:16 2023

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'stella'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link lCursor Cursor

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#0d1a16', '#8c4151', '#5c7d3e', '#736439', '#3e4a7d', '#794180', '#38665b', '#95b1ae', '#2f3c39', '#ff758f', '#b9fc7e', '#f2d479', '#7e95fc', '#f382ff', '#7ee6cc', '#e7ffff']
  endif
  if get(g:, 'stella_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#e7ffff guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#e7ffff guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#e7ffff guibg=#0d1a16 gui=NONE cterm=NONE
    hi Terminal guifg=#e7ffff guibg=#0d1a16 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#2f3c39 gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#5c7d3e guibg=#e7ffff gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#2f3c39 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#2f3c39 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#f2d479 guibg=#2f3c39 gui=NONE cterm=NONE
  hi DiffAdd guifg=#e7ffff guibg=#5c7d3e gui=NONE cterm=NONE
  hi DiffChange guifg=#e7ffff guibg=#736439 gui=NONE cterm=NONE
  hi DiffDelete guifg=#e7ffff guibg=#8c4151 gui=NONE cterm=NONE
  hi DiffText guifg=#0d1a16 guibg=#95b1ae gui=bold cterm=bold
  hi Directory guifg=#7e95fc guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#7e95fc guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e7ffff guibg=#8c4151 gui=NONE cterm=NONE
  hi FoldColumn guifg=#7e95fc guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#7ee6cc guibg=#2f3c39 gui=NONE cterm=NONE
  hi IncSearch guifg=#0d1a16 guibg=#b9fc7e gui=NONE cterm=NONE
  hi LineNr guifg=#95b1ae guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#e7ffff guibg=#736439 gui=NONE cterm=NONE
  hi ModeMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MoreMsg guifg=#b9fc7e guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#7e95fc guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#e7ffff guibg=#0d1a16 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#e7ffff guibg=#0d1a16 gui=NONE cterm=NONE
  hi PmenuSel guifg=#0d1a16 guibg=#f2d479 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#95b1ae guibg=#2f3c39 gui=NONE cterm=NONE
  hi Question guifg=#b9fc7e guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#2f3c39 gui=NONE cterm=NONE
  hi SignColumn guifg=#7e95fc guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#7e95fc guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#ff758f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellCap guifg=NONE guibg=NONE guisp=#7e95fc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellLocal guifg=NONE guibg=NONE guisp=#7ee6cc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellRare guifg=NONE guibg=NONE guisp=#f382ff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi StatusLine guifg=#0d1a16 guibg=#95b1ae gui=NONE cterm=NONE
  hi StatusLineNC guifg=#e7ffff guibg=#2f3c39 gui=NONE cterm=NONE
  hi TabLine guifg=#95b1ae guibg=#2f3c39 gui=NONE cterm=NONE
  hi TabLineFill guifg=#0d1a16 guibg=#95b1ae gui=NONE cterm=NONE
  hi TabLineSel guifg=#e7ffff guibg=#0d1a16 gui=bold cterm=bold
  hi Title guifg=#f382ff guibg=NONE gui=bold cterm=bold
  hi VertSplit guifg=#e7ffff guibg=#2f3c39 gui=NONE cterm=NONE
  hi Visual guifg=#0d1a16 guibg=#e7ffff gui=NONE cterm=NONE
  hi VisualNOS guifg=#e7ffff guibg=#0d1a16 gui=bold,underline cterm=bold,underline
  hi WarningMsg guifg=#ff758f guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#0d1a16 guibg=#f2d479 gui=NONE cterm=NONE
  hi debugPC guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi debugBreakpoint guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#0d1a16 guibg=#0d1a16 gui=NONE cterm=NONE
  hi Comment guifg=#95b1ae guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#7ee6cc guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#e7ffff guibg=#8c4151 gui=NONE cterm=NONE
  hi Identifier guifg=#7e95fc guibg=NONE gui=bold cterm=bold
  hi PreProc guifg=#f382ff guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#ff758f guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#f2d479 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#f2d479 guibg=NONE gui=italic,reverse cterm=italic,reverse
  hi Type guifg=#b9fc7e guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#7e95fc guibg=NONE gui=underline cterm=underline
  hi! link CursorIM Cursor
  hi ToolbarLine guifg=NONE guibg=#2f3c39 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#0d1a16 guibg=#f2d479 gui=bold cterm=bold
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Todo gui=reverse cterm=reverse
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#0f0500', '#94011c', '#428507', '#7a5d06', '#071e85', '#7a0587', '#006e52', '#d0d9d9', '#5a5350', '#ff8299', '#b0e880', '#ffe28c', '#8093e8', '#f48fff', '#99ffe6', '#faffff']
  endif
  if get(g:, 'stella_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#0f0500 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#0f0500 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#0f0500 guibg=#faffff gui=NONE cterm=NONE
    hi Terminal guifg=#0f0500 guibg=#faffff gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#d0d9d9 gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#b0e880 guibg=#5a5350 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#d0d9d9 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#d0d9d9 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#7a0587 guibg=#d0d9d9 gui=NONE cterm=NONE
  hi DiffAdd guifg=#0f0500 guibg=#b0e880 gui=NONE cterm=NONE
  hi DiffChange guifg=#0f0500 guibg=#ffe28c gui=NONE cterm=NONE
  hi DiffDelete guifg=#0f0500 guibg=#ff8299 gui=NONE cterm=NONE
  hi DiffText guifg=#faffff guibg=#5a5350 gui=bold cterm=bold
  hi Directory guifg=#006e52 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#006e52 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#0f0500 guibg=#ff8299 gui=NONE cterm=NONE
  hi FoldColumn guifg=#006e52 guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#071e85 guibg=#d0d9d9 gui=NONE cterm=NONE
  hi IncSearch guifg=#faffff guibg=#428507 gui=NONE cterm=NONE
  hi LineNr guifg=#5a5350 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#0f0500 guibg=#ffe28c gui=NONE cterm=NONE
  hi ModeMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MoreMsg guifg=#428507 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#006e52 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#0f0500 guibg=#faffff gui=NONE cterm=NONE
  hi PmenuSbar guifg=#0f0500 guibg=#faffff gui=NONE cterm=NONE
  hi PmenuSel guifg=#0f0500 guibg=#ffe28c gui=NONE cterm=NONE
  hi PmenuThumb guifg=#d0d9d9 guibg=#5a5350 gui=NONE cterm=NONE
  hi Question guifg=#428507 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#d0d9d9 gui=NONE cterm=NONE
  hi SignColumn guifg=#006e52 guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#006e52 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#ff8299 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellCap guifg=NONE guibg=NONE guisp=#006e52 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellLocal guifg=NONE guibg=NONE guisp=#071e85 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi SpellRare guifg=NONE guibg=NONE guisp=#7a0587 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
  hi StatusLine guifg=#0f0500 guibg=#d0d9d9 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#faffff guibg=#5a5350 gui=NONE cterm=NONE
  hi TabLine guifg=#5a5350 guibg=#d0d9d9 gui=NONE cterm=NONE
  hi TabLineFill guifg=#faffff guibg=#5a5350 gui=NONE cterm=NONE
  hi TabLineSel guifg=#0f0500 guibg=#faffff gui=bold cterm=bold
  hi Title guifg=#7a0587 guibg=NONE gui=bold cterm=bold
  hi VertSplit guifg=#5a5350 guibg=#d0d9d9 gui=NONE cterm=NONE
  hi Visual guifg=#faffff guibg=#0f0500 gui=NONE cterm=NONE
  hi VisualNOS guifg=#0f0500 guibg=#faffff gui=bold,underline cterm=bold,underline
  hi WarningMsg guifg=#94011c guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#5a5350 guibg=#ffe28c gui=NONE cterm=NONE
  hi debugPC guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi debugBreakpoint guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#faffff guibg=#faffff gui=NONE cterm=NONE
  hi Comment guifg=#5a5350 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#071e85 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#0f0500 guibg=#ff8299 gui=NONE cterm=NONE
  hi Identifier guifg=#006e52 guibg=NONE gui=bold cterm=bold
  hi PreProc guifg=#7a0587 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#94011c guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#7a5d06 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#7a5d06 guibg=NONE gui=italic,reverse cterm=italic,reverse
  hi Type guifg=#428507 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#071e85 guibg=NONE gui=underline cterm=underline
  hi! link CursorIM Cursor
  hi ToolbarLine guifg=NONE guibg=#d0d9d9 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#0f0500 guibg=#ffe28c gui=bold cterm=bold
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Todo gui=reverse cterm=reverse
  endif
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'stella_transp_bg', 0)
      hi Normal ctermfg=195 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=195 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=195 ctermbg=234 cterm=NONE
      hi Terminal ctermfg=195 ctermbg=234 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=65 ctermbg=195 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
    hi CursorLineNr ctermfg=222 ctermbg=237 cterm=NONE
    hi DiffAdd ctermfg=195 ctermbg=65 cterm=NONE
    hi DiffChange ctermfg=195 ctermbg=58 cterm=NONE
    hi DiffDelete ctermfg=195 ctermbg=125 cterm=NONE
    hi DiffText ctermfg=234 ctermbg=109 cterm=bold
    hi Directory ctermfg=69 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=69 ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=195 ctermbg=125 cterm=NONE
    hi FoldColumn ctermfg=69 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=79 ctermbg=237 cterm=NONE
    hi IncSearch ctermfg=234 ctermbg=156 cterm=NONE
    hi LineNr ctermfg=109 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=195 ctermbg=58 cterm=NONE
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=156 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=69 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=195 ctermbg=234 cterm=NONE
    hi PmenuSbar ctermfg=195 ctermbg=234 cterm=NONE
    hi PmenuSel ctermfg=234 ctermbg=222 cterm=NONE
    hi PmenuThumb ctermfg=109 ctermbg=237 cterm=NONE
    hi Question ctermfg=156 ctermbg=NONE cterm=NONE
    hi Search ctermfg=NONE ctermbg=237 cterm=NONE
    hi SignColumn ctermfg=69 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=69 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=underline
    hi StatusLine ctermfg=234 ctermbg=109 cterm=NONE
    hi StatusLineNC ctermfg=195 ctermbg=237 cterm=NONE
    hi TabLine ctermfg=109 ctermbg=237 cterm=NONE
    hi TabLineFill ctermfg=234 ctermbg=109 cterm=NONE
    hi TabLineSel ctermfg=195 ctermbg=234 cterm=bold
    hi Title ctermfg=213 ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=195 ctermbg=237 cterm=NONE
    hi Visual ctermfg=234 ctermbg=195 cterm=NONE
    hi VisualNOS ctermfg=195 ctermbg=234 cterm=bold,underline
    hi WarningMsg ctermfg=204 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=234 ctermbg=222 cterm=NONE
    hi debugPC ctermfg=fg ctermbg=NONE cterm=NONE
    hi debugBreakpoint ctermfg=fg ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=234 ctermbg=234 cterm=NONE
    hi Comment ctermfg=109 ctermbg=NONE cterm=italic
    hi Constant ctermfg=79 ctermbg=NONE cterm=NONE
    hi Error ctermfg=195 ctermbg=125 cterm=NONE
    hi Identifier ctermfg=69 ctermbg=NONE cterm=bold
    hi PreProc ctermfg=213 ctermbg=NONE cterm=NONE
    hi Special ctermfg=204 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=222 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=222 ctermbg=NONE cterm=italic,reverse
    hi Type ctermfg=156 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=69 ctermbg=NONE cterm=underline
    hi! link CursorIM Cursor
    hi ToolbarLine ctermfg=NONE ctermbg=237 cterm=NONE
    hi ToolbarButton ctermfg=234 ctermbg=222 cterm=bold
    if !s:italics
      hi Comment cterm=NONE
      hi Todo cterm=reverse
    endif
  else
    " Light background
    if get(g:, 'stella_transp_bg', 0)
      hi Normal ctermfg=232 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=232 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=232 ctermbg=231 cterm=NONE
      hi Terminal ctermfg=232 ctermbg=231 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=188 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=150 ctermbg=240 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=188 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=188 cterm=NONE
    hi CursorLineNr ctermfg=90 ctermbg=188 cterm=NONE
    hi DiffAdd ctermfg=232 ctermbg=150 cterm=NONE
    hi DiffChange ctermfg=232 ctermbg=222 cterm=NONE
    hi DiffDelete ctermfg=232 ctermbg=211 cterm=NONE
    hi DiffText ctermfg=231 ctermbg=240 cterm=bold
    hi Directory ctermfg=29 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=29 ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=232 ctermbg=211 cterm=NONE
    hi FoldColumn ctermfg=29 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=18 ctermbg=188 cterm=NONE
    hi IncSearch ctermfg=231 ctermbg=28 cterm=NONE
    hi LineNr ctermfg=240 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=232 ctermbg=222 cterm=NONE
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=28 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=29 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=232 ctermbg=231 cterm=NONE
    hi PmenuSbar ctermfg=232 ctermbg=231 cterm=NONE
    hi PmenuSel ctermfg=232 ctermbg=222 cterm=NONE
    hi PmenuThumb ctermfg=188 ctermbg=240 cterm=NONE
    hi Question ctermfg=28 ctermbg=NONE cterm=NONE
    hi Search ctermfg=NONE ctermbg=188 cterm=NONE
    hi SignColumn ctermfg=29 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=29 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=underline
    hi StatusLine ctermfg=232 ctermbg=188 cterm=NONE
    hi StatusLineNC ctermfg=231 ctermbg=240 cterm=NONE
    hi TabLine ctermfg=240 ctermbg=188 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=240 cterm=NONE
    hi TabLineSel ctermfg=232 ctermbg=231 cterm=bold
    hi Title ctermfg=90 ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=240 ctermbg=188 cterm=NONE
    hi Visual ctermfg=231 ctermbg=232 cterm=NONE
    hi VisualNOS ctermfg=232 ctermbg=231 cterm=bold,underline
    hi WarningMsg ctermfg=88 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=240 ctermbg=222 cterm=NONE
    hi debugPC ctermfg=fg ctermbg=NONE cterm=NONE
    hi debugBreakpoint ctermfg=fg ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=231 ctermbg=231 cterm=NONE
    hi Comment ctermfg=240 ctermbg=NONE cterm=italic
    hi Constant ctermfg=18 ctermbg=NONE cterm=NONE
    hi Error ctermfg=232 ctermbg=211 cterm=NONE
    hi Identifier ctermfg=29 ctermbg=NONE cterm=bold
    hi PreProc ctermfg=90 ctermbg=NONE cterm=NONE
    hi Special ctermfg=88 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=94 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=94 ctermbg=NONE cterm=italic,reverse
    hi Type ctermfg=28 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=18 ctermbg=NONE cterm=underline
    hi! link CursorIM Cursor
    hi ToolbarLine ctermfg=NONE ctermbg=188 cterm=NONE
    hi ToolbarButton ctermfg=232 ctermbg=222 cterm=bold
    if !s:italics
      hi Comment cterm=NONE
      hi Todo cterm=reverse
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'stella_transp_bg', 0)
      hi Normal ctermfg=White ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=White ctermbg=Black cterm=NONE
      hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=DarkGreen ctermbg=White cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi CursorLineNr ctermfg=LightYellow ctermbg=DarkGrey cterm=NONE
    hi DiffAdd ctermfg=White ctermbg=DarkGreen cterm=NONE
    hi DiffChange ctermfg=White ctermbg=DarkYellow cterm=NONE
    hi DiffDelete ctermfg=White ctermbg=DarkRed cterm=NONE
    hi DiffText ctermfg=Black ctermbg=LightGrey cterm=bold
    hi Directory ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=White ctermbg=DarkRed cterm=NONE
    hi FoldColumn ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi Folded ctermfg=LightCyan ctermbg=DarkGrey cterm=NONE
    hi IncSearch ctermfg=Black ctermbg=LightGreen cterm=NONE
    hi LineNr ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=White ctermbg=DarkYellow cterm=NONE
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=LightGreen ctermbg=NONE cterm=NONE
    hi NonText ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=White ctermbg=Black cterm=NONE
    hi PmenuSbar ctermfg=White ctermbg=Black cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=LightYellow cterm=NONE
    hi PmenuThumb ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi Question ctermfg=LightGreen ctermbg=NONE cterm=NONE
    hi Search ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi SignColumn ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=underline
    hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi StatusLineNC ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi TabLine ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Black cterm=bold
    hi Title ctermfg=LightMagenta ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi Visual ctermfg=Black ctermbg=White cterm=NONE
    hi VisualNOS ctermfg=White ctermbg=Black cterm=bold,underline
    hi WarningMsg ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=Black ctermbg=LightYellow cterm=NONE
    hi debugPC ctermfg=fg ctermbg=NONE cterm=NONE
    hi debugBreakpoint ctermfg=fg ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=Black ctermbg=Black cterm=NONE
    hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
    hi Constant ctermfg=LightCyan ctermbg=NONE cterm=NONE
    hi Error ctermfg=White ctermbg=DarkRed cterm=NONE
    hi Identifier ctermfg=LightBlue ctermbg=NONE cterm=bold
    hi PreProc ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Statement ctermfg=LightYellow ctermbg=NONE cterm=NONE
    hi Todo ctermfg=LightYellow ctermbg=NONE cterm=italic,reverse
    hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=LightBlue ctermbg=NONE cterm=underline
    hi! link CursorIM Cursor
    hi ToolbarLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi ToolbarButton ctermfg=Black ctermbg=LightYellow cterm=bold
    if !s:italics
      hi Comment cterm=NONE
      hi Todo cterm=reverse
    endif
  else
    " Light background
    if get(g:, 'stella_transp_bg', 0)
      hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=Black ctermbg=White cterm=NONE
      hi Terminal ctermfg=Black ctermbg=White cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=LightGreen ctermbg=DarkGrey cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLineNr ctermfg=DarkMagenta ctermbg=LightGrey cterm=NONE
    hi DiffAdd ctermfg=Black ctermbg=LightGreen cterm=NONE
    hi DiffChange ctermfg=Black ctermbg=LightYellow cterm=NONE
    hi DiffDelete ctermfg=Black ctermbg=LightRed cterm=NONE
    hi DiffText ctermfg=White ctermbg=DarkGrey cterm=bold
    hi Directory ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=Black ctermbg=LightRed cterm=NONE
    hi FoldColumn ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi Folded ctermfg=DarkBlue ctermbg=LightGrey cterm=NONE
    hi IncSearch ctermfg=White ctermbg=DarkGreen cterm=NONE
    hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=Black ctermbg=LightYellow cterm=NONE
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=DarkGreen ctermbg=NONE cterm=NONE
    hi NonText ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=Black ctermbg=White cterm=NONE
    hi PmenuSbar ctermfg=Black ctermbg=White cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=LightYellow cterm=NONE
    hi PmenuThumb ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi Question ctermfg=DarkGreen ctermbg=NONE cterm=NONE
    hi Search ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi SignColumn ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=DarkCyan ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=underline
    hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi StatusLineNC ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi TabLine ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=White cterm=bold
    hi Title ctermfg=DarkMagenta ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
    hi Visual ctermfg=White ctermbg=Black cterm=NONE
    hi VisualNOS ctermfg=Black ctermbg=White cterm=bold,underline
    hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=DarkGrey ctermbg=LightYellow cterm=NONE
    hi debugPC ctermfg=fg ctermbg=NONE cterm=NONE
    hi debugBreakpoint ctermfg=fg ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=White ctermbg=White cterm=NONE
    hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=italic
    hi Constant ctermfg=DarkBlue ctermbg=NONE cterm=NONE
    hi Error ctermfg=Black ctermbg=LightRed cterm=NONE
    hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=bold
    hi PreProc ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Statement ctermfg=DarkYellow ctermbg=NONE cterm=NONE
    hi Todo ctermfg=DarkYellow ctermbg=NONE cterm=italic,reverse
    hi Type ctermfg=DarkGreen ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=DarkBlue ctermbg=NONE cterm=underline
    hi! link CursorIM Cursor
    hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi ToolbarButton ctermfg=Black ctermbg=LightYellow cterm=bold
    if !s:italics
      hi Comment cterm=NONE
      hi Todo cterm=reverse
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color:  darkblack     #0D1A16   ~         Black
" Color:  brightblack   #2F3C39   ~         DarkGrey
" Color:  darkwhite     #95B1AE   ~         LightGrey
" Color:  brightwhite   #E7FFFF   ~         White
" Color:  darkred       #8C4151   ~         DarkRed
" Color:  darkyellow    #736439   ~         DarkYellow
" Color:  darkgreen     #5C7D3E   ~         DarkGreen
" Color:  darkcyan      #38665B   ~         DarkCyan
" Color:  darkblue      #3E4A7D   ~         DarkBlue
" Color:  darkmagenta   #794180   ~         DarkMagenta
" Color:  brightred     #FF758F   ~         LightRed
" Color:  brightyellow  #F2D479   ~         LightYellow
" Color:  brightgreen   #B9FC7E   ~         LightGreen
" Color:  brightcyan    #7EE6CC   ~         LightCyan
" Color:  brightblue    #7E95FC   ~         LightBlue
" Color:  brightmagenta #F382FF   ~         LightMagenta
" Term colors:  darkblack     darkred         darkgreen     darkyellow
" Term colors:  darkblue      darkmagenta     darkcyan      darkwhite
" Term colors:  brightblack   brightred       brightgreen   brightyellow
" Term colors:  brightblue    brightmagenta   brightcyan    brightwhite
" Background: light
" Color:  darkblack     #0F0500   ~         Black
" Color:  brightblack   #5A5350   ~         DarkGrey
" Color:  darkwhite     #D0D9D9   ~         LightGrey
" Color:  brightwhite   #FAFFFF   ~         White
" Color:  darkred       #94011C   ~         DarkRed
" Color:  darkyellow    #7A5D06   ~         DarkYellow
" Color:  darkgreen     #428507   ~         DarkGreen
" Color:  darkcyan      #006E52   ~         DarkCyan
" Color:  darkblue      #071E85   ~         DarkBlue
" Color:  darkmagenta   #7A0587   ~         DarkMagenta
" Color:  brightred     #FF8299   ~         LightRed
" Color:  brightyellow  #FFE28C   ~         LightYellow
" Color:  brightgreen   #B0E880   ~         LightGreen
" Color:  brightcyan    #99FFE6   ~         LightCyan
" Color:  brightblue    #8093E8   ~         LightBlue
" Color:  brightmagenta #F48FFF   ~         LightMagenta
" Term colors:  darkblack     darkred         darkgreen     darkyellow
" Term colors:  darkblue      darkmagenta     darkcyan      darkwhite
" Term colors:  brightblack   brightred       brightgreen   brightyellow
" Term colors:  brightblue    brightmagenta   brightcyan    brightwhite
" Background: any
" vim: et ts=8 sw=2 sts=2
